### PR TITLE
CertiFail Test Selector Tool

### PR DESCRIPTION
**Pull request by FasihMunirMalik**

### CODE REVIEW

**Comment by ChristianBirchler** [comment]
Thanks for the submission @FasihMunirMalik. Can you briefly confirm that this tool is for the ICST tool competition?

**Comment by FasihMunirMalik** [comment]
Yes. For the other tool competition I might submit a different tool

**Comment by ChristianBirchler** [comment]
@FasihMunirMalik , may I ask you to have only changes in your own tool directory? This helps me for the evaluation when all competitors have their files only in their own subdirectory of the `tools` directory. Thanks a lot!

**Comment by FasihMunirMalik** [comment]
> @FasihMunirMalik , may I ask you to have only changes in your own tool directory? This helps me for the evaluation when all competitors have their files only in their own subdirectory of the `tools` directory. Thanks a lot!

Hi  @ChristianBirchler , I just rechecked, my tool (CertiFail) is located in the following subdirectory tools/certifail. Please let me know if that doesn't work.

**Comment by ChristianBirchler** [comment]
That is perfect @FasihMunirMalik. Thanks!

The only thing I also want to ask is to undo the changes of the sample tool. The idea is that when I do the merge only your directory should be added to the repository.

**Review by ChristianBirchler — CHANGES_REQUESTED** [review]
The authors are advised to undo the changes in the sample tool.

**Comment by FasihMunirMalik** [comment]
@ChristianBirchler I have reverted the changes. I now see that the only files changed for this pull request are located inside the certifail subdirectory. let me know if that works.

**Review by ChristianBirchler — APPROVED** [review]
That is great! Thanks @FasihMunirMalik.

**Comment by mattiafazzini** [comment]
@FasihMunirMalik This is Mattia Fazzini, one of the co-chairs of the Self-Driving Car Testing Tool Competition. We would like to collect information about all the authors of the tool. Can you send the first name, surname, email, and affiliation for all the authors to mfazzini@umn.edu? Thank you in advance for this.

**Comment by mattiafazzini** [comment]
@FasihMunirMalik please send us an email with the information requested above as soon as you can.

**Pull request merged**
