### PR TITLE
DRVN Tool- SDC Competition ICST'25

### PR DESCRIPTION
**Pull request by checkdgt**
Proposed tool for 18th IEEE International Conference on Software Testing, Verification and Validation (ICST) 2025 - Tool Competition: Self-Driving Car Testing.

Tool name: DRVN

### CODE REVIEW

**Review by ChristianBirchler — APPROVED** [review]
merge for evaluation

**Comment by ChristianBirchler** [comment]
Hi @checkdgt, may I ask what Nvidia driver version and host OS you have used for your tool? Probably I have to adjust the version on the evaluation platform.

**Comment by ChristianBirchler** [comment]
Yes this helps. Thanks a lot @checkdgt. 

Of course I will let you know if I have to update the Dockerfile so that you can verify that your tool does not have any disadvantages.

**Comment by checkdgt** [comment]
Hi @ChristianBirchler, thanks for double checking this. As long as there's no error message such as **'Could not find cuda drivers on your machine, GPU will not be used.'** then it's all good. I get the same warnings when I run this on my machine but as long as the GPU is registered correctly then all should run correctly 😃

**Comment by ChristianBirchler** [comment]
Thanks @checkdgt for the quick reply! I never had an error stating that CUDA could not be found. Hence, all should be fine.

I was simply not sure if you had the same messages or not. I want to ensure that your tool performs well with the GPU as intended for the evaluation so that you don't have any disadvantages. If you think those warnings need to be fixed, let me know.

**Comment by checkdgt** [comment]
@ChristianBirchler, yeah no worries, thanks for checking, but everything looks good from here. Same warnings, so there shouldn't be any detrimental impact from it 😄 .... I think you're good to test 😉

**Comment by mattiafazzini** [comment]
@checkdgt This is Mattia Fazzini, one of the co-chairs of the Self-Driving Car Testing Tool Competition. We would like to collect information about all the authors of the tool. Can you send the first name, surname, email, and affiliation for all the authors to mfazzini@umn.edu? Thank you in advance for this.

**Pull request merged**
